# Generated by Django 2.2.7 on 2019-12-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lbeportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NocComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comment from NOC team:')),
                ('user', models.CharField(max_length=64, verbose_name='User:')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lbeportal.SiteVendor')),
            ],
        ),
    ]
