# Generated by Django 2.2.7 on 2019-12-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nocportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noccomment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='lbeportal.SiteVendor'),
        ),
    ]
