# Generated by Django 2.2.7 on 2020-01-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbeportal', '0002_sitevendor_engineer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevendor',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='division',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='instalation_date',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='lan_assistance',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='local_contact',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='office_hours',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='parrarelorhot',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='technical_contact',
        ),
        migrations.RemoveField(
            model_name='sitevendor',
            name='voip_assistance',
        ),
    ]
