# Generated by Django 2.2.7 on 2020-01-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lbeportal', '0003_auto_20200128_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitevendor',
            old_name='engineer',
            new_name='user',
        ),
    ]
